#!/bin/sh

cd konference

ASTERISK_INSTALL_DIR=$1
ASTERISK_SRC_DIR=$2

make ASTERISK_SRC_DIR=$ASTERISK_SRC_DIR ASTERISK_SRC_VERSION=1100 &&
make install \
  ASTERISK_INSTALL_DIR=$ASTERISK_INSTALL_DIR \
  ASTERISK_SRC_DIR=$ASTERISK_SRC_DIR \
  ASTERISK_SRC_VERSION=1100 \

cd ..
